version: '2'

services:
    voip:
        build: asterisk13/
        ports:
            - 5038:5038
            - 5060:5060/udp
            - 10000-10040:10000-10040/udp
        volumes:
            - ./asterisk13/config:/etc/asterisk 
        depends_on:
            - db

    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ./mysql/config:/etc/mysql/conf.d
            - ./mysql/on-container-create-sql-dumps:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=123
